
//lv50 Chansey
TrainerBattle_EventScript_Trainer855::
 	trainerbattle_single TRAINER_855, TrainerBattle_Text_Trainer855_Intro, TrainerBattle_Text_Trainer855_Defeated
 	msgbox TrainerBattle_Text_Trainer855_Post, MSGBOX_AUTOCLOSE
 	end
 
TrainerBattle_Text_Trainer855_Intro:
	.string "What's the matter?\n"
	.string "Scared of my special POKéMON?$"

TrainerBattle_Text_Trainer855_Defeated:
	.string "My CHANSEY wasn't special enough!$"

TrainerBattle_Text_Trainer855_Post:
	.string "Don't worry CHANSEY, you're still\n"
	.string "special to me.$"
